@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtYXJpYUBnb21lei5jb20iLCJjb250YWN0byI6OTExMTExMTExLCJpYXQiOjE3NjQ0MzcxNzUsImV4cCI6MTc2NDQ0MDc3NX0.OKhd0JwIQ6j7NhDlUoW0UnwLyxCHomF9zxLjJ-0MDJI

###Obtener todas las publicaciones
POST http://localhost:3000/pets/auth/login
Content-Type: application/json

{
    "email": "maria@gomez.com",
    "password": "pass123"
}

###Registro de usuario
POST http://localhost:3000/pets/auth/register
Content-Type: application/json

{
    "us_nombre": "Tiara",
    "us_email": "tiara@tiara.com",
    "us_contrasena": "pass123",
    "us_contacto": "987654321"
}

###Acceder a una ruta protegida, el token obtiene al realizar login
GET http://localhost:3000/pets/auth/protegido
Authorization: Bearer {{token}}




###Obtener todas las publicaciones
GET http://localhost:3000/pets/publicaciones

###Obtener todas las publicaciones
GET http://localhost:3000/pets/verDetalles/1

petsRouter.get("/verDetalles", obtenerDetalles);

###Crear una publicacion
POST http://localhost:3000/pets/publicaciones/crear
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "pu_titulo": "Nuevo",
    "pu_descripcion": "Lo mas nuevo",
    "pu_ubicacion": "Lo novedoso",
    "pu_imagen": "nuevo.png",
    "pu_imagenes": [
        "new2.png",
        "new3.png"
    ]
}


###Obtener todas las publicaciones
GET http://localhost:3000/pets/posts

###Obtener todas las etiquetas
GET http://localhost:3000/pets/tags

